version: '3.8'

services:
  app:
    build: .
    container_name: node-notes-app
    ports:
      - "4001:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql87@,
      MYSQL_DATABASE: node
      MYSQL_USER: xuv
      MYSQL_PASSWORD: Xuv700@,
    ports:
      - "3303:3306"
    volumes:
      - mysql_data1:/var/lib/mysql

volumes:
  mysql_data1:
